### ISSUE TITLE
Brexit

### ISSUE THREAD

**Issue by b-n** [timmyRS/is-eu-member#4]
Stumbled across this package. 'GB' might not be so handy in the list anymore.

**Comment by Sainan** [comment]
Should be fixed now

**Comment by ArcadeRenegade** [comment]
for anyone using this repository for GDPR. UK has it's own data protection law that is similar. so you may want to include GB anyways.

https://ico.org.uk/for-organisations/dp-at-the-end-of-the-transition-period/transition-period-faqs/#:~:text=The%20EU%20GDPR%20is%20an,with%20UK%20data%20protection%20law.
